### ISSUE TITLE
Question: Syntax highlighting?

### ISSUE THREAD

**Issue by DylanPiercey** [AntonioVdlC/html-template-tag#1]
I've seen quasi literal html functions before but I have yet to find a good way to add syntax highlighting (in sublime) for these within javascript.

I am just curious what you use or if you don't care about syntax highlighting the html?

**Comment by AntonioVdlC** [comment]
Hi Dylan!

It seems like syntax highlighting for HTML in JavaScript template literals is still not there in Sublime (or in VSCode for that matter, as I have recently switched to it).

There are already a few issues and discussions going on on adding that feature in Sublime [here](https://github.com/sublimehq/Packages/issues/179), but in the meantime [this](https://forum.sublimetext.com/t/javascript-es6-template-literals-syntax-for-html/18242/2) seems to do the trick.

Hope that helps!
