### ISSUE TITLE
Error with typescript and ESM

### ISSUE THREAD

**Issue by ZachHaber** [AntonioVdlC/html-template-tag#196]
When working with `moduleResolution: nodeNext`, the type definitions are interpreted by typescript as being commonjs. It doesn't seem to register the existence of the `module` property in the package.json.

So, the easiest way to resolve this to make TS happy is to add the `exports` property to the package.json and output a separate .d.ts file for the esmodule output.

```json
  "exports":{
    ".":{
      "import": {
        "types":"./dist/index.d.mts",
        "default":"./dist/index.esm.js"
      },
      "require":{
        "types":"./dist/index.d.ts",
        "default":"./dist/index.cjs.js"
      }
    }
  },
```

**Comment by AntonioVdlC** [comment]
Thanks for raising this issue, and sorry it took so long for me to have a look at this!
